name: craftmentor_backend
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.4.0

dependencies:
  envied: ^0.5.4+1
  http: ^1.2.0
  mysql_client: ^0.0.27
  postgres: ^3.2.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  uuid: ^4.3.3
  postgresql2: ^1.6.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
